
export const metadata = {
  title: 'layout new',
  description: 'Generated by create next app',
}

export default function LayoutPost({ children }) {
  return (
     <>
   
      {children}</>  
  )
}
