"use client";

import Image from "next/image";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Login() {
  return (
    <>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        login page
      </main>
    </>
  );
}
