"use client";

import Image from "next/image";
import { useSelector, useDispatch } from "react-redux";
import { increment, decrement } from "../redux/features/counterSlice";
import { useGetPokemonByNameQuery } from "../redux/services/userApi";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Login() {
  const count = useSelector((state) => state.counter.value);
  const dispatch = useDispatch();
  const { isLoading, isFetching, data, error } = useGetPokemonByNameQuery(1);
  const handleIncrement = () => {
    dispatch(increment());
  };

  const handleDecrement = () => {
    dispatch(decrement());
  };
  return (
    <>
      <div>
        {console.log("data",data)}
        <h1>Count: {count}</h1>
        <button onClick={handleIncrement}>Increment</button>
        <button onClick={handleDecrement}>Decrement</button>
      </div>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        login page
      </main>
    </>
  );
}
