import Navbar from "./clientComponent/main/Navbar";
import Footer from "./clientComponent/main/Footer";
import "./globals.css";

import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = localFont({
  src: [
    {
      path: "../../../public/fonts/Kanit-Black.ttf",
      style: "normal",
      weight: "600",
    },
    {
      path: "../../../public/fonts/Kanit-BlackItalic.ttf",
      style: "italic",
      weight: "300",
    },
    {
      path: "../../../public/fonts/Kanit-Bold.ttf",
      style: "bold",
      weight: "500",
    },
    {
      path: "../../../public/fonts/Kanit-ExtraLight.ttf",
      style: "normal",
      weight: "100",
    },
  ],
  variable: "--font-kanit",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${kanit.variable} font-sans font-thin`}
    >
      <head></head>
      <body className="bg-myCustomBgBody h-screen p-0 m-0 overflow-x-hidden ">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
