"use client";
import Image from "next/image";

import BannerSlider from "./clientComponent/slider/BannerSlider";
import axios from "axios";
import Link from "next/link";

import { useState } from "react";
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

export const metadata = {
  title: "text meta tags ",
  description: "Generated by create next app",
};
const Home = async () => {
  const postsData = await fecthPosts();

  return (
    <>
      <div class="grid grid-cols-3 gap-4">
        <div class="col-span-2 bg-gray-900">
          <BannerSlider />
        </div>
        <div class="col-span-1">
          <div className="bg-red-900">05</div>
          <div className="bg-red-500">06</div>
        </div>
      </div>
      <div className="block md:flex justify-center w-full  flex-wrap">
        {postsData.map((post) => (
          <div className="md:w-1/4  w-full p-5" key={post.id}>
            <Link href={`/posts/${post.id}`}>
              <div className="singleCardPost ">
                <Image src={post.imageUrl} alt="" width="500" height="160" />
                <h1 className="text-lg">{post.title} </h1>
                <p className="text-sm">{post.body}</p>
                <button type="btn" className="btnMore ">
                  click more
                </button>
              </div>
            </Link>
          </div>
        ))}

        {/* <Pagination
          count={postsData.length}
          page={1}
          rowsPerPage={10}
          color="primary"
        /> */}
      </div>
    </>
  );
};
export default Home;
async function fecthPosts() {
  const { data } = await axios.get("http://localhost:3001/posts");
  return data;
}
