import "./globals.css";


import { Inter } from "next/font/google";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <head>
      </head>
      <body className={`bg-red-900 h-screen p-0 m-0`}>
      
        {children}
        
       
      </body>
    </html>
  );
}
